name: PR

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        name: Checkout code
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - uses: burrunan/gradle-cache-action@v1
        name: Build and test
        with:
          job-id: jdk17
          arguments: clean test jacocoTestReport
          gradle-version: wrapper
